### ISSUE TITLE
Open connection after reading a collection

### ISSUE THREAD

**Issue by GitHubUser67** [grijjy/DelphiMongoDB#1]
After reading a collection (or any read write operation), the MongoDb server reports one open connection.
This also occurs with the MongoDBTests.
Am I missing something?

**Comment by allendrennan** [comment]
Connections are managed by the underlying socket and protocol and are maintained alive in order to reduce reconnect between transactions across the same connection.  This is relatively arbitrary with IOCP, Epoll and other scale sockets in our model.

**Comment by GitHubUser67** [comment]
Thanks for your explanation!
By the way, I love this framework and use it extensively!
