### ISSUE TITLE
Use driver with MongoDB replica sets - is it possible?

### ISSUE THREAD

**Issue by RadiRadiesel2** [grijjy/DelphiMongoDB#12]
Connection information to the driver  (primary, secondary) can be passed through a comma separated list when using TMongoClient.Create(). Internally, all connection information get stored into a connections array. But it look like, when connecting to a MongoDB, it only uses the primary connection information passed in the Create() function. So if the current primary gets unavailable, a new elected primary never gets detected/used. 
Is it actually possible to use replica sets with this driver, or does this need to be enhanced?
Thx in advance!

**Comment by allendrennan** [comment]
The driver does not contain replica set support, although we welcome any additions or changes.

**Comment by RadiRadiesel2** [comment]
Already working on it, thx! And I could see, that you already merged a pull request... Thank you!
