### ISSUE TITLE
I Have Memory Issues

### ISSUE THREAD

**Issue by hillfolk** [grijjy/DelphiMongoDB#3]
First I thank you. I use a lot of your library.
I have one problem. 
Memory usage does not decrease while using the Find function.
I look up data repeatedly in a short cycle.
Am I misusing it?
Interval: 10 ~ 15 sec
Data Count: 100 ~ 500
Document is too Big  One document is over 30k

**Comment by ritsaert** [comment]
I have the same issue here. Iterating over a simple collection using .Find() will give a higher memory usage with each document accessed. It looks like the documents are kept in memory. I even tried to 'free' the document in memory by calling ToNil() / Clear() with no result in memory usage. The only difference with the issue of hillfolk is that our datasets are huge and while churning data we get an out of memory exception.

**Comment by allendrennan** [comment]
We made a small change for this.  Please pull the library and let me know if it persists.  If it does, please provide an example code block.

**Comment by hillfolk** [comment]
Thank. The problem was solved.
But there was another problem.
CancelIoEx function can not be found.
I use Windows 10 and using Delphi berlin version 10.1.
Is this function not supported on Windows 10?

**Comment by allendrennan** [comment]
We typically only test on the latest version of Delphi.  It would seem that it was only included in the Windows headers in the most recent versions of Delphi.  It isn't needed in this situation to resolve the problem, but it's good practice.

**Comment by ritsaert** [comment]
Tested and fixes the growing memory usage.

**Comment by timanagement** [comment]
Greetings, as it would use with a dataset, because in my case the Filter did not work ?
